# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 069e62a26fc938c26031a94ae3d64fad83a2258c1399dd3009dcf09c83002c0db281f231b0975922f8af5b14e70d983f4a1c6989c83f46a051f66329733d6b25

test:
  secret_key_base: f49f7c90c8e3768f1ecb823add79ba7f94db6002b070398110f9d88abe3883344e5c38730b5dd16d6b926d121692e08907f8d39b40723c3069595bb32c9da72e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
